### ISSUE TITLE
Negotiation Rounds against Compatibility Report

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/ExpressBusServices#23]
Eventually I have to face it.

With Compatibility Report making such a fuss over this + latest P2P DLC releasing, I had to check the situation of EBS + 81 Tiles.

Apparently, as I load up my main save file, the game crashed with a blank map.

I am currently testing with this version of 81 tiles due to the release of the latest DLC:

https://steamcommunity.com/sharedfiles/filedetails/?id=2862121823

I will have to determine which mod is causing problems, but this can be a good place to start.

**Comment by Vectorial1024** [comment]
Nah, it turns out I forgot to turn off the "tiles unlocked" option from Extended Game Options when enabling 81 Tiles.

Which means one thing: negotiation rounds with Compatibility Report.

Unfortunate that it has come down to this.

**Comment by Vectorial1024** [comment]
I will be following up on this.

https://github.com/Finwickle/CompatibilityReport/issues/55

**Comment by RuszinZsolt** [comment]
> Eventually I have to face it.
> 
> With Compatibility Report making such a fuss over this + latest P2P DLC releasing, I had to check the situation of EBS + 81 Tiles.
> 
> Apparently, as I load up my main save file, the game crashed with a blank map.
> 
> I am currently testing with this version of 81 tiles due to the release of the latest DLC:
> 
> https://steamcommunity.com/sharedfiles/filedetails/?id=2862121823
> 
> I will have to determine which mod is causing problems, but this can be a good place to start.

**I am happy of your concerns. Please also make sure, that IPT2 FIX is around.**

**Comment by chameleon-tbn** [comment]
Have answered in the other thread btw

**Comment by Vectorial1024** [comment]
Main issue solved.

I have also suggested something extra on the other side.

Still, thanks for the help!
