### ISSUE TITLE
Mod is broken: side effects caused by incorrect termini detection

### ISSUE THREAD

**Issue by Vectorial1024** [Vectorial1024/ExpressBusServices#8]
Steam user reports this mod being broken and that buses failed to "bunch". This seems to align with my recent, personal observations during my CSL environment reset that this mod would throw Harmony exceptions + buses failed to "bunch".

Putting this on hold until I have the time to investigate.

**Comment by Vectorial1024** [comment]
Steam user further adds correlation with the usage of non-multiple-of-5 transport assets. I am aware of Multiple Of Five but am not aware of it causing problems because I personally avoid Non-Multiple Of Five already.

This seems like a variation of the Citizen Runaway Problem.

**Comment by Verdigo76** [comment]
My city has 150k and over 150 buses. I haven't noticed any bus skipping a stop but if no one is there is doesn't hang around for the default time either.  I also haven't noticed any other behavior changes. I assume this is all because the mod is "broken". I'm using TM:PE as well and haven't received any errors.

Edit: Correction, Buses to hang around at the station(I.E. first bus stop) for around 12-15 seconds when boarding. If there was a way to gives this as a modifiable option by the user that would also be great.

**Comment by Vectorial1024** [comment]
Now that I have (recently) spent some extended time observing this mod, I finally noticed something is wrong:

~The built-in IPT2 compat is acting up when IPT2 is unavailable (um), so that, through some yet-to-discover pathway, buses fail to stay on the first stop as advertised.~ Actually it seems to be Commuter Destination acting up, but still.

~Will need to spend some time, really transferring whatever stuff related to IPT2 to the plugin for IPT2...~ Edit: really no need to move the patches around, because things are fine as is; the patches are not too complicated, and so. unless it is truly necessary, I really do NOT want to make a new mod for patches etc.

**Comment by Vectorial1024** [comment]
@Verdigo76 as for the "modifiable option by the user", you may be interested in a relevant discussion on the other side https://github.com/klyte45/TransportLinesManager/issues/206

**Comment by Vectorial1024** [comment]
Again, to re-state the problem: the logic used to determine which stop is the terminus was faulty, so buses failed to unbunch at termini as advertised. Adding the fact that other components were working correctly, it means that if other "guidance" mods such as TLM were not used, buses never unbunched. This is unintended.

The above bug should be fixed in the latest Steam release. Closing this.
